-- DentAIstudy: Study Suite tables
-- Run after chat_history.sql in Supabase Dashboard → SQL Editor.

create extension if not exists "pgcrypto";

-- =========================
-- Shared updated_at helper
-- =========================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================
-- Flashcards
-- =========================
create table if not exists public.flashcard_decks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Untitled deck',
  source_type text not null default 'notes',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists flashcard_decks_user_updated_idx
  on public.flashcard_decks (user_id, updated_at desc, created_at desc);

create table if not exists public.flashcards (
  id bigint generated by default as identity primary key,
  deck_id uuid not null references public.flashcard_decks(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  front text not null,
  back text not null,
  position integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists flashcards_deck_position_idx
  on public.flashcards (deck_id, position asc, id asc);

create or replace function public.touch_flashcard_deck_updated_at()
returns trigger
language plpgsql
as $$
begin
  update public.flashcard_decks
  set updated_at = now()
  where id = coalesce(new.deck_id, old.deck_id);

  return coalesce(new, old);
end;
$$;

drop trigger if exists flashcard_decks_set_updated_at on public.flashcard_decks;
create trigger flashcard_decks_set_updated_at
before update on public.flashcard_decks
for each row execute function public.set_updated_at();

drop trigger if exists flashcards_touch_deck on public.flashcards;
create trigger flashcards_touch_deck
after insert or update or delete on public.flashcards
for each row execute function public.touch_flashcard_deck_updated_at();

-- =========================
-- Quizzes
-- =========================
create table if not exists public.study_quizzes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Untitled quiz',
  difficulty text not null default 'normal' check (difficulty in ('easy', 'normal', 'hard')),
  question_count integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists study_quizzes_user_created_idx
  on public.study_quizzes (user_id, created_at desc);

create table if not exists public.study_quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id uuid not null references public.study_quizzes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  question text not null,
  options jsonb not null,
  correct_index integer not null default 0,
  explanation text,
  position integer not null default 1,
  created_at timestamptz not null default now(),
  constraint study_quiz_questions_options_array check (jsonb_typeof(options) = 'array')
);

create index if not exists study_quiz_questions_quiz_position_idx
  on public.study_quiz_questions (quiz_id, position asc, id asc);

create table if not exists public.study_quiz_attempts (
  id bigint generated by default as identity primary key,
  quiz_id uuid not null references public.study_quizzes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer not null default 0,
  total integer not null default 0,
  answers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists study_quiz_attempts_user_created_idx
  on public.study_quiz_attempts (user_id, created_at desc);

create or replace function public.touch_study_quiz_updated_at()
returns trigger
language plpgsql
as $$
begin
  update public.study_quizzes
  set updated_at = now()
  where id = coalesce(new.quiz_id, old.quiz_id);

  return coalesce(new, old);
end;
$$;

drop trigger if exists study_quizzes_set_updated_at on public.study_quizzes;
create trigger study_quizzes_set_updated_at
before update on public.study_quizzes
for each row execute function public.set_updated_at();

drop trigger if exists study_quiz_questions_touch_quiz on public.study_quiz_questions;
create trigger study_quiz_questions_touch_quiz
after insert or update or delete on public.study_quiz_questions
for each row execute function public.touch_study_quiz_updated_at();

-- =========================
-- RLS
-- =========================
alter table public.flashcard_decks enable row level security;
alter table public.flashcards enable row level security;
alter table public.study_quizzes enable row level security;
alter table public.study_quiz_questions enable row level security;
alter table public.study_quiz_attempts enable row level security;

drop policy if exists "Users can CRUD their flashcard decks" on public.flashcard_decks;
create policy "Users can CRUD their flashcard decks"
on public.flashcard_decks
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can CRUD their flashcards" on public.flashcards;
create policy "Users can CRUD their flashcards"
on public.flashcards
for all
using (
  auth.uid() = user_id
  and exists (
    select 1 from public.flashcard_decks d
    where d.id = flashcards.deck_id
      and d.user_id = auth.uid()
  )
)
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.flashcard_decks d
    where d.id = flashcards.deck_id
      and d.user_id = auth.uid()
  )
);

drop policy if exists "Users can CRUD their study quizzes" on public.study_quizzes;
create policy "Users can CRUD their study quizzes"
on public.study_quizzes
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can CRUD their study quiz questions" on public.study_quiz_questions;
create policy "Users can CRUD their study quiz questions"
on public.study_quiz_questions
for all
using (
  auth.uid() = user_id
  and exists (
    select 1 from public.study_quizzes q
    where q.id = study_quiz_questions.quiz_id
      and q.user_id = auth.uid()
  )
)
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.study_quizzes q
    where q.id = study_quiz_questions.quiz_id
      and q.user_id = auth.uid()
  )
);

drop policy if exists "Users can CRUD their quiz attempts" on public.study_quiz_attempts;
create policy "Users can CRUD their quiz attempts"
on public.study_quiz_attempts
for all
using (
  auth.uid() = user_id
  and exists (
    select 1 from public.study_quizzes q
    where q.id = study_quiz_attempts.quiz_id
      and q.user_id = auth.uid()
  )
)
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.study_quizzes q
    where q.id = study_quiz_attempts.quiz_id
      and q.user_id = auth.uid()
  )
);
